[package]
name = "beach-cabana-desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
beach-cabana-host = { path = "../../host" }
crossterm = "0.27"
ratatui = { version = "0.26", default-features = false, features = ["crossterm"] }

